# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtcavity.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(845, 724)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.line = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frequency = QtWidgets.QDoubleSpinBox(self.widget)
        self.frequency.setDecimals(2)
        self.frequency.setMaximum(99999.0)
        self.frequency.setProperty("value", 1300.0)
        self.frequency.setObjectName("frequency")
        self.horizontalLayout_11.addWidget(self.frequency)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.roq = QtWidgets.QDoubleSpinBox(self.widget)
        self.roq.setMaximum(100000.0)
        self.roq.setProperty("value", 1024.0)
        self.roq.setObjectName("roq")
        self.horizontalLayout_13.addWidget(self.roq)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_13.addWidget(self.label_10)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.horizontalLayout_13, 1, 2, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.q0 = QtWidgets.QDoubleSpinBox(self.widget)
        self.q0.setMaximum(1000000000000.0)
        self.q0.setProperty("value", 10000000000.0)
        self.q0.setObjectName("q0")
        self.horizontalLayout_18.addWidget(self.q0)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_18.addWidget(self.label_12)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem2)
        self.gridLayout_3.addLayout(self.horizontalLayout_18, 2, 2, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.length = QtWidgets.QDoubleSpinBox(self.widget)
        self.length.setDecimals(5)
        self.length.setProperty("value", 1.0)
        self.length.setObjectName("length")
        self.horizontalLayout_17.addWidget(self.length)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_17.addWidget(self.label_11)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem3)
        self.gridLayout_3.addLayout(self.horizontalLayout_17, 2, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.detuning = QtWidgets.QDoubleSpinBox(self.widget)
        self.detuning.setDecimals(3)
        self.detuning.setMaximum(1000000.0)
        self.detuning.setObjectName("detuning")
        self.horizontalLayout_12.addWidget(self.detuning)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.gridLayout_3.addLayout(self.horizontalLayout_12, 4, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.detuning_angle = QtWidgets.QDoubleSpinBox(self.widget)
        self.detuning_angle.setMinimum(-179.0)
        self.detuning_angle.setMaximum(179.0)
        self.detuning_angle.setObjectName("detuning_angle")
        self.horizontalLayout_15.addWidget(self.detuning_angle)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_15.addWidget(self.label_14)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem5)
        self.gridLayout_3.addLayout(self.horizontalLayout_15, 4, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.line_4 = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_2.addWidget(self.line_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.qext = QtWidgets.QDoubleSpinBox(self.widget)
        self.qext.setMaximum(1000000000000.0)
        self.qext.setProperty("value", 5000000.0)
        self.qext.setObjectName("qext")
        self.horizontalLayout_16.addWidget(self.qext)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem6)
        self.gridLayout_4.addLayout(self.horizontalLayout_16, 0, 0, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.beta = QtWidgets.QDoubleSpinBox(self.widget)
        self.beta.setDecimals(4)
        self.beta.setMaximum(100000.0)
        self.beta.setObjectName("beta")
        self.horizontalLayout_23.addWidget(self.beta)
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_23.addWidget(self.label_18)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem7)
        self.gridLayout_4.addLayout(self.horizontalLayout_23, 1, 0, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.line_impedance = QtWidgets.QDoubleSpinBox(self.widget)
        self.line_impedance.setMaximum(1000.0)
        self.line_impedance.setProperty("value", 50.0)
        self.line_impedance.setObjectName("line_impedance")
        self.horizontalLayout_20.addWidget(self.line_impedance)
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_20.addWidget(self.label_16)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem8)
        self.gridLayout_4.addLayout(self.horizontalLayout_20, 0, 1, 1, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.turn_ratio = QtWidgets.QDoubleSpinBox(self.widget)
        self.turn_ratio.setMaximum(1000000000000.0)
        self.turn_ratio.setObjectName("turn_ratio")
        self.horizontalLayout_22.addWidget(self.turn_ratio)
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_22.addWidget(self.label_17)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem9)
        self.gridLayout_4.addLayout(self.horizontalLayout_22, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.line_5 = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_5.sizePolicy().hasHeightForWidth())
        self.line_5.setSizePolicy(sizePolicy)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_3.addWidget(self.line_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.fill_time = QtWidgets.QDoubleSpinBox(self.widget)
        self.fill_time.setDecimals(6)
        self.fill_time.setMaximum(10000.0)
        self.fill_time.setProperty("value", 100.0)
        self.fill_time.setObjectName("fill_time")
        self.horizontalLayout_24.addWidget(self.fill_time)
        self.label_19 = QtWidgets.QLabel(self.widget)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_24.addWidget(self.label_19)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem10)
        self.gridLayout_2.addLayout(self.horizontalLayout_24, 0, 0, 1, 1)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.fill_gradient = QtWidgets.QDoubleSpinBox(self.widget)
        self.fill_gradient.setMaximum(10000.0)
        self.fill_gradient.setProperty("value", 10.0)
        self.fill_gradient.setObjectName("fill_gradient")
        self.horizontalLayout_32.addWidget(self.fill_gradient)
        self.label_22 = QtWidgets.QLabel(self.widget)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_32.addWidget(self.label_22)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem11)
        self.gridLayout_2.addLayout(self.horizontalLayout_32, 1, 1, 1, 1)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.fill_voltage = QtWidgets.QDoubleSpinBox(self.widget)
        self.fill_voltage.setMaximum(1000000.0)
        self.fill_voltage.setObjectName("fill_voltage")
        self.horizontalLayout_31.addWidget(self.fill_voltage)
        self.label_21 = QtWidgets.QLabel(self.widget)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_31.addWidget(self.label_21)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem12)
        self.gridLayout_2.addLayout(self.horizontalLayout_31, 1, 0, 1, 1)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.fill_power = QtWidgets.QDoubleSpinBox(self.widget)
        self.fill_power.setMaximum(1000000000.0)
        self.fill_power.setObjectName("fill_power")
        self.horizontalLayout_28.addWidget(self.fill_power)
        self.label_20 = QtWidgets.QLabel(self.widget)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_28.addWidget(self.label_20)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem13)
        self.gridLayout_2.addLayout(self.horizontalLayout_28, 0, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem14)
        self.checkBox_5 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_36.addWidget(self.checkBox_5)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem15)
        self.verticalLayout_5.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.line_7 = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_7.sizePolicy().hasHeightForWidth())
        self.line_7.setSizePolicy(sizePolicy)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_4.addWidget(self.line_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.flat_voltage = QtWidgets.QDoubleSpinBox(self.widget)
        self.flat_voltage.setMaximum(1000000.0)
        self.flat_voltage.setObjectName("flat_voltage")
        self.horizontalLayout_14.addWidget(self.flat_voltage)
        self.label_25 = QtWidgets.QLabel(self.widget)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_14.addWidget(self.label_25)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem16)
        self.gridLayout_5.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.flat_time = QtWidgets.QDoubleSpinBox(self.widget)
        self.flat_time.setDecimals(6)
        self.flat_time.setMaximum(10000.0)
        self.flat_time.setProperty("value", 100.0)
        self.flat_time.setObjectName("flat_time")
        self.horizontalLayout_19.addWidget(self.flat_time)
        self.label_23 = QtWidgets.QLabel(self.widget)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_19.addWidget(self.label_23)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem17)
        self.gridLayout_5.addLayout(self.horizontalLayout_19, 0, 0, 1, 1)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.flat_power = QtWidgets.QDoubleSpinBox(self.widget)
        self.flat_power.setMaximum(1000000000.0)
        self.flat_power.setObjectName("flat_power")
        self.horizontalLayout_42.addWidget(self.flat_power)
        self.label_24 = QtWidgets.QLabel(self.widget)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_42.addWidget(self.label_24)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_42.addItem(spacerItem18)
        self.gridLayout_5.addLayout(self.horizontalLayout_42, 0, 1, 1, 1)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.flat_gradient = QtWidgets.QDoubleSpinBox(self.widget)
        self.flat_gradient.setMaximum(10000.0)
        self.flat_gradient.setProperty("value", 10.0)
        self.flat_gradient.setObjectName("flat_gradient")
        self.horizontalLayout_43.addWidget(self.flat_gradient)
        self.label_26 = QtWidgets.QLabel(self.widget)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_43.addWidget(self.label_26)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem19)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem20)
        self.gridLayout_5.addLayout(self.horizontalLayout_43, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.line_6 = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_6.sizePolicy().hasHeightForWidth())
        self.line_6.setSizePolicy(sizePolicy)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_5.addWidget(self.line_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.decay_time = QtWidgets.QDoubleSpinBox(self.widget)
        self.decay_time.setDecimals(6)
        self.decay_time.setMaximum(10000.0)
        self.decay_time.setProperty("value", 100.0)
        self.decay_time.setObjectName("decay_time")
        self.horizontalLayout_33.addWidget(self.decay_time)
        self.label_29 = QtWidgets.QLabel(self.widget)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_33.addWidget(self.label_29)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem21)
        self.gridLayout.addLayout(self.horizontalLayout_33, 0, 0, 1, 1)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.ql = QtWidgets.QDoubleSpinBox(self.widget)
        self.ql.setMaximum(1000000000000.0)
        self.ql.setObjectName("ql")
        self.horizontalLayout_39.addWidget(self.ql)
        self.label_28 = QtWidgets.QLabel(self.widget)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_39.addWidget(self.label_28)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem22)
        self.gridLayout.addLayout(self.horizontalLayout_39, 1, 1, 1, 1)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.bandwidth = QtWidgets.QDoubleSpinBox(self.widget)
        self.bandwidth.setMaximum(1000000.0)
        self.bandwidth.setObjectName("bandwidth")
        self.horizontalLayout_25.addWidget(self.bandwidth)
        self.label_27 = QtWidgets.QLabel(self.widget)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_25.addWidget(self.label_27)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem23)
        self.gridLayout.addLayout(self.horizontalLayout_25, 1, 0, 1, 1)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.decay_tau = QtWidgets.QDoubleSpinBox(self.widget)
        self.decay_tau.setMaximum(10000.0)
        self.decay_tau.setProperty("value", 100.0)
        self.decay_tau.setObjectName("decay_tau")
        self.horizontalLayout_41.addWidget(self.decay_tau)
        self.label_30 = QtWidgets.QLabel(self.widget)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_41.addWidget(self.label_30)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem24)
        self.gridLayout.addLayout(self.horizontalLayout_41, 0, 1, 1, 1)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.n_tau = QtWidgets.QDoubleSpinBox(self.widget)
        self.n_tau.setMaximum(1000.0)
        self.n_tau.setProperty("value", 0.0)
        self.n_tau.setObjectName("n_tau")
        self.horizontalLayout_46.addWidget(self.n_tau)
        self.label_38 = QtWidgets.QLabel(self.widget)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_46.addWidget(self.label_38)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_46.addItem(spacerItem25)
        self.gridLayout.addLayout(self.horizontalLayout_46, 2, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.line_3 = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_6.addWidget(self.line_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem26)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_2.addWidget(self.checkBox_3)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.horizontalLayout_8.addWidget(self.groupBox_2)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem27)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.line_2 = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_7.addWidget(self.line_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.spinBox = QtWidgets.QSpinBox(self.widget)
        self.spinBox.setMaximum(1000000)
        self.spinBox.setProperty("value", 1000)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_9.addWidget(self.spinBox)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem28)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_9.addWidget(self.pushButton)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem29)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_9.addWidget(self.pushButton_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(self.widget_2)
        self.tabWidget.setObjectName("tabWidget")
        self.gradienttab = QtWidgets.QWidget()
        self.gradienttab.setObjectName("gradienttab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gradienttab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.gradienttab)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.gradienttab)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.verticalLayout.addWidget(self.graphicsView_2)
        spacerItem30 = QtWidgets.QSpacerItem(20, 196, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem30)
        self.tabWidget.addTab(self.gradienttab, "")
        self.energytab = QtWidgets.QWidget()
        self.energytab.setObjectName("energytab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.energytab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.energytab)
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.verticalLayout_6.addWidget(self.graphicsView_4)
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.energytab)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.verticalLayout_6.addWidget(self.graphicsView_3)
        spacerItem31 = QtWidgets.QSpacerItem(20, 196, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem31)
        self.tabWidget.addTab(self.energytab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.graphicsView_6 = QtWidgets.QGraphicsView(self.tab_3)
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.verticalLayout_7.addWidget(self.graphicsView_6)
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.tab_3)
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.verticalLayout_7.addWidget(self.graphicsView_5)
        spacerItem32 = QtWidgets.QSpacerItem(20, 196, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem32)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_8.addWidget(self.tabWidget)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_31 = QtWidgets.QLabel(self.widget_2)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_44.addWidget(self.label_31)
        self.line_8 = QtWidgets.QFrame(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_8.sizePolicy().hasHeightForWidth())
        self.line_8.setSizePolicy(sizePolicy)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_44.addWidget(self.line_8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_34 = QtWidgets.QLabel(self.widget_2)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_11.addWidget(self.label_34)
        self.label_46 = QtWidgets.QLabel(self.widget_2)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_11.addWidget(self.label_46)
        self.label_45 = QtWidgets.QLabel(self.widget_2)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_11.addWidget(self.label_45)
        self.label_44 = QtWidgets.QLabel(self.widget_2)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_11.addWidget(self.label_44)
        self.horizontalLayout_45.addLayout(self.verticalLayout_11)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_33 = QtWidgets.QLabel(self.widget_2)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_10.addWidget(self.label_33)
        self.label_43 = QtWidgets.QLabel(self.widget_2)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_10.addWidget(self.label_43)
        self.label_42 = QtWidgets.QLabel(self.widget_2)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_10.addWidget(self.label_42)
        self.label_41 = QtWidgets.QLabel(self.widget_2)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_10.addWidget(self.label_41)
        self.label_40 = QtWidgets.QLabel(self.widget_2)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_10.addWidget(self.label_40)
        self.horizontalLayout_45.addLayout(self.verticalLayout_10)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_39 = QtWidgets.QLabel(self.widget_2)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_9.addWidget(self.label_39)
        self.label_37 = QtWidgets.QLabel(self.widget_2)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_9.addWidget(self.label_37)
        self.label_36 = QtWidgets.QLabel(self.widget_2)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_9.addWidget(self.label_36)
        self.label_35 = QtWidgets.QLabel(self.widget_2)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_9.addWidget(self.label_35)
        self.label_32 = QtWidgets.QLabel(self.widget_2)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_9.addWidget(self.label_32)
        self.horizontalLayout_45.addLayout(self.verticalLayout_9)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_45.addItem(spacerItem33)
        self.verticalLayout_8.addLayout(self.horizontalLayout_45)
        spacerItem34 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem34)
        self.horizontalLayout_10.addWidget(self.widget_2)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Cavity"))
        self.label_9.setText(_translate("Form", "Frequency [MHz]"))
        self.label_10.setText(_translate("Form", "R/Q [Ohm]"))
        self.label_12.setText(_translate("Form", "Q0"))
        self.label_11.setText(_translate("Form", "Length [m]"))
        self.label_13.setText(_translate("Form", "Detuning [Hz]"))
        self.label_14.setText(_translate("Form", "Detuning angle [deg]"))
        self.label_2.setText(_translate("Form", "Coupling"))
        self.label_15.setText(_translate("Form", "Qext"))
        self.label_18.setText(_translate("Form", "Beta"))
        self.label_16.setText(_translate("Form", "Line impedance [Ohm]"))
        self.label_17.setText(_translate("Form", "Turn ratio n"))
        self.label_4.setText(_translate("Form", "Filling"))
        self.label_19.setText(_translate("Form", "Time [ms]"))
        self.label_22.setText(_translate("Form", "Steady state gradient  [MV/m]"))
        self.label_21.setText(_translate("Form", "Fwd Voltage [V]"))
        self.label_20.setText(_translate("Form", "Fwd Power [W]"))
        self.checkBox_5.setText(_translate("Form", "Lock with flattop"))
        self.label_3.setText(_translate("Form", "Flattop"))
        self.label_25.setText(_translate("Form", "Fwd Voltage [V]"))
        self.label_23.setText(_translate("Form", "Time [ms]"))
        self.label_24.setText(_translate("Form", "Fwd Power [W]"))
        self.label_26.setText(_translate("Form", "Steady state gradient [MV/m]"))
        self.label_5.setText(_translate("Form", "Decay"))
        self.label_29.setText(_translate("Form", "Time [ms]"))
        self.label_28.setText(_translate("Form", "QL"))
        self.label_27.setText(_translate("Form", "Bandwidth [Hz]"))
        self.label_30.setText(_translate("Form", "Tau [ms]"))
        self.label_38.setText(_translate("Form", "Time [x tau]"))
        self.label_6.setText(_translate("Form", "Show"))
        self.groupBox_2.setTitle(_translate("Form", "Displayed traces"))
        self.checkBox_3.setText(_translate("Form", "Probe"))
        self.checkBox_2.setText(_translate("Form", "Forward"))
        self.checkBox.setText(_translate("Form", "Reflected"))
        self.label_7.setText(_translate("Form", "Simulation"))
        self.label_8.setText(_translate("Form", "Simulation points"))
        self.pushButton.setText(_translate("Form", "Load"))
        self.pushButton_2.setText(_translate("Form", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gradienttab), _translate("Form", "Gradient/Voltage"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.energytab), _translate("Form", "Energy/Power"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Phase"))
        self.label_31.setText(_translate("Form", "Consumption"))
        self.label_34.setText(_translate("Form", "Filling diss. energy [mJ]"))
        self.label_46.setText(_translate("Form", "Flattop diss. energy [mJ]"))
        self.label_45.setText(_translate("Form", "Decay diss. energy [mJ]"))
        self.label_44.setText(_translate("Form", "Total diss. energy [mJ]"))
        self.label_33.setText(_translate("Form", "TextLabel"))
        self.label_43.setText(_translate("Form", "TextLabel"))
        self.label_42.setText(_translate("Form", "TextLabel"))
        self.label_41.setText(_translate("Form", "TextLabel"))
        self.label_40.setText(_translate("Form", "TextLabel"))
        self.label_39.setText(_translate("Form", "TextLabel"))
        self.label_37.setText(_translate("Form", "TextLabel"))
        self.label_36.setText(_translate("Form", "TextLabel"))
        self.label_35.setText(_translate("Form", "TextLabel"))
        self.label_32.setText(_translate("Form", "TextLabel"))

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtcavity.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(921, 896)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.line = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frequency = QtWidgets.QDoubleSpinBox(self.widget)
        self.frequency.setDecimals(2)
        self.frequency.setMaximum(99999.0)
        self.frequency.setProperty("value", 1300.0)
        self.frequency.setObjectName("frequency")
        self.horizontalLayout_11.addWidget(self.frequency)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.roq = QtWidgets.QDoubleSpinBox(self.widget)
        self.roq.setMaximum(100000.0)
        self.roq.setProperty("value", 1024.0)
        self.roq.setObjectName("roq")
        self.horizontalLayout_13.addWidget(self.roq)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_13.addWidget(self.label_10)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.gridLayout_3.addLayout(self.horizontalLayout_13, 1, 2, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.q0 = QtWidgets.QDoubleSpinBox(self.widget)
        self.q0.setMaximum(1000000000000.0)
        self.q0.setProperty("value", 10000000000.0)
        self.q0.setObjectName("q0")
        self.horizontalLayout_18.addWidget(self.q0)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_18.addWidget(self.label_12)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem2)
        self.gridLayout_3.addLayout(self.horizontalLayout_18, 2, 2, 1, 1)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.length = QtWidgets.QDoubleSpinBox(self.widget)
        self.length.setDecimals(5)
        self.length.setProperty("value", 1.0)
        self.length.setObjectName("length")
        self.horizontalLayout_17.addWidget(self.length)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_17.addWidget(self.label_11)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem3)
        self.gridLayout_3.addLayout(self.horizontalLayout_17, 2, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.detuning = QtWidgets.QDoubleSpinBox(self.widget)
        self.detuning.setDecimals(3)
        self.detuning.setMinimum(-1000000.0)
        self.detuning.setMaximum(1000000.0)
        self.detuning.setObjectName("detuning")
        self.horizontalLayout_12.addWidget(self.detuning)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem4)
        self.gridLayout_3.addLayout(self.horizontalLayout_12, 4, 0, 1, 1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.detuning_angle = QtWidgets.QDoubleSpinBox(self.widget)
        self.detuning_angle.setMinimum(-179.0)
        self.detuning_angle.setMaximum(179.0)
        self.detuning_angle.setObjectName("detuning_angle")
        self.horizontalLayout_15.addWidget(self.detuning_angle)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_15.addWidget(self.label_14)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem5)
        self.gridLayout_3.addLayout(self.horizontalLayout_15, 4, 2, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.line_4 = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_2.addWidget(self.line_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.qext = QtWidgets.QDoubleSpinBox(self.widget)
        self.qext.setMaximum(1000000000000.0)
        self.qext.setProperty("value", 5000000.0)
        self.qext.setObjectName("qext")
        self.horizontalLayout_16.addWidget(self.qext)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem6)
        self.gridLayout_4.addLayout(self.horizontalLayout_16, 0, 0, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.beta = QtWidgets.QDoubleSpinBox(self.widget)
        self.beta.setDecimals(4)
        self.beta.setMaximum(100000.0)
        self.beta.setObjectName("beta")
        self.horizontalLayout_23.addWidget(self.beta)
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_23.addWidget(self.label_18)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem7)
        self.gridLayout_4.addLayout(self.horizontalLayout_23, 1, 0, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.line_impedance = QtWidgets.QDoubleSpinBox(self.widget)
        self.line_impedance.setMaximum(1000.0)
        self.line_impedance.setProperty("value", 50.0)
        self.line_impedance.setObjectName("line_impedance")
        self.horizontalLayout_20.addWidget(self.line_impedance)
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_20.addWidget(self.label_16)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem8)
        self.gridLayout_4.addLayout(self.horizontalLayout_20, 0, 1, 1, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.turn_ratio = QtWidgets.QDoubleSpinBox(self.widget)
        self.turn_ratio.setMaximum(1000000000000.0)
        self.turn_ratio.setObjectName("turn_ratio")
        self.horizontalLayout_22.addWidget(self.turn_ratio)
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_22.addWidget(self.label_17)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem9)
        self.gridLayout_4.addLayout(self.horizontalLayout_22, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.line_5 = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_5.sizePolicy().hasHeightForWidth())
        self.line_5.setSizePolicy(sizePolicy)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_3.addWidget(self.line_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.fill_time = QtWidgets.QDoubleSpinBox(self.widget)
        self.fill_time.setDecimals(6)
        self.fill_time.setMaximum(10000.0)
        self.fill_time.setProperty("value", 100.0)
        self.fill_time.setObjectName("fill_time")
        self.horizontalLayout_24.addWidget(self.fill_time)
        self.label_19 = QtWidgets.QLabel(self.widget)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_24.addWidget(self.label_19)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem10)
        self.gridLayout_2.addLayout(self.horizontalLayout_24, 0, 0, 1, 1)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.fill_gradient = QtWidgets.QDoubleSpinBox(self.widget)
        self.fill_gradient.setMaximum(10000.0)
        self.fill_gradient.setProperty("value", 10.0)
        self.fill_gradient.setObjectName("fill_gradient")
        self.horizontalLayout_32.addWidget(self.fill_gradient)
        self.label_22 = QtWidgets.QLabel(self.widget)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_32.addWidget(self.label_22)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem11)
        self.gridLayout_2.addLayout(self.horizontalLayout_32, 1, 1, 1, 1)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.fill_voltage = QtWidgets.QDoubleSpinBox(self.widget)
        self.fill_voltage.setMaximum(1000000.0)
        self.fill_voltage.setObjectName("fill_voltage")
        self.horizontalLayout_31.addWidget(self.fill_voltage)
        self.label_21 = QtWidgets.QLabel(self.widget)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_31.addWidget(self.label_21)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_31.addItem(spacerItem12)
        self.gridLayout_2.addLayout(self.horizontalLayout_31, 1, 0, 1, 1)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.fill_power = QtWidgets.QDoubleSpinBox(self.widget)
        self.fill_power.setMaximum(1000000000.0)
        self.fill_power.setObjectName("fill_power")
        self.horizontalLayout_28.addWidget(self.fill_power)
        self.label_20 = QtWidgets.QLabel(self.widget)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_28.addWidget(self.label_20)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_28.addItem(spacerItem13)
        self.gridLayout_2.addLayout(self.horizontalLayout_28, 0, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem14)
        self.checkBox_5 = QtWidgets.QCheckBox(self.widget)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_36.addWidget(self.checkBox_5)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_36.addItem(spacerItem15)
        self.verticalLayout_5.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.line_7 = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_7.sizePolicy().hasHeightForWidth())
        self.line_7.setSizePolicy(sizePolicy)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.horizontalLayout_4.addWidget(self.line_7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.flat_voltage = QtWidgets.QDoubleSpinBox(self.widget)
        self.flat_voltage.setMaximum(1000000.0)
        self.flat_voltage.setObjectName("flat_voltage")
        self.horizontalLayout_14.addWidget(self.flat_voltage)
        self.label_25 = QtWidgets.QLabel(self.widget)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_14.addWidget(self.label_25)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem16)
        self.gridLayout_5.addLayout(self.horizontalLayout_14, 1, 0, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.flat_time = QtWidgets.QDoubleSpinBox(self.widget)
        self.flat_time.setDecimals(6)
        self.flat_time.setMaximum(10000.0)
        self.flat_time.setProperty("value", 100.0)
        self.flat_time.setObjectName("flat_time")
        self.horizontalLayout_19.addWidget(self.flat_time)
        self.label_23 = QtWidgets.QLabel(self.widget)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_19.addWidget(self.label_23)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem17)
        self.gridLayout_5.addLayout(self.horizontalLayout_19, 0, 0, 1, 1)
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.flat_power = QtWidgets.QDoubleSpinBox(self.widget)
        self.flat_power.setMaximum(1000000000.0)
        self.flat_power.setObjectName("flat_power")
        self.horizontalLayout_42.addWidget(self.flat_power)
        self.label_24 = QtWidgets.QLabel(self.widget)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_42.addWidget(self.label_24)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_42.addItem(spacerItem18)
        self.gridLayout_5.addLayout(self.horizontalLayout_42, 0, 1, 1, 1)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.flat_gradient = QtWidgets.QDoubleSpinBox(self.widget)
        self.flat_gradient.setMaximum(10000.0)
        self.flat_gradient.setProperty("value", 10.0)
        self.flat_gradient.setObjectName("flat_gradient")
        self.horizontalLayout_43.addWidget(self.flat_gradient)
        self.label_26 = QtWidgets.QLabel(self.widget)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_43.addWidget(self.label_26)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem19)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem20)
        self.gridLayout_5.addLayout(self.horizontalLayout_43, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.line_6 = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_6.sizePolicy().hasHeightForWidth())
        self.line_6.setSizePolicy(sizePolicy)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_5.addWidget(self.line_6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.decay_time = QtWidgets.QDoubleSpinBox(self.widget)
        self.decay_time.setDecimals(6)
        self.decay_time.setMaximum(10000.0)
        self.decay_time.setProperty("value", 100.0)
        self.decay_time.setObjectName("decay_time")
        self.horizontalLayout_33.addWidget(self.decay_time)
        self.label_29 = QtWidgets.QLabel(self.widget)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_33.addWidget(self.label_29)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem21)
        self.gridLayout.addLayout(self.horizontalLayout_33, 0, 0, 1, 1)
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.ql = QtWidgets.QDoubleSpinBox(self.widget)
        self.ql.setMaximum(1000000000000.0)
        self.ql.setObjectName("ql")
        self.horizontalLayout_39.addWidget(self.ql)
        self.label_28 = QtWidgets.QLabel(self.widget)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_39.addWidget(self.label_28)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem22)
        self.gridLayout.addLayout(self.horizontalLayout_39, 1, 1, 1, 1)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.bandwidth = QtWidgets.QDoubleSpinBox(self.widget)
        self.bandwidth.setMaximum(1000000.0)
        self.bandwidth.setObjectName("bandwidth")
        self.horizontalLayout_25.addWidget(self.bandwidth)
        self.label_27 = QtWidgets.QLabel(self.widget)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_25.addWidget(self.label_27)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem23)
        self.gridLayout.addLayout(self.horizontalLayout_25, 1, 0, 1, 1)
        self.horizontalLayout_41 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_41.setObjectName("horizontalLayout_41")
        self.decay_tau = QtWidgets.QDoubleSpinBox(self.widget)
        self.decay_tau.setMaximum(10000.0)
        self.decay_tau.setProperty("value", 100.0)
        self.decay_tau.setObjectName("decay_tau")
        self.horizontalLayout_41.addWidget(self.decay_tau)
        self.label_30 = QtWidgets.QLabel(self.widget)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_41.addWidget(self.label_30)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_41.addItem(spacerItem24)
        self.gridLayout.addLayout(self.horizontalLayout_41, 0, 1, 1, 1)
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.n_tau = QtWidgets.QDoubleSpinBox(self.widget)
        self.n_tau.setMaximum(1000.0)
        self.n_tau.setProperty("value", 0.0)
        self.n_tau.setObjectName("n_tau")
        self.horizontalLayout_46.addWidget(self.n_tau)
        self.label_38 = QtWidgets.QLabel(self.widget)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout_46.addWidget(self.label_38)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_46.addItem(spacerItem25)
        self.gridLayout.addLayout(self.horizontalLayout_46, 2, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.line_3 = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_6.addWidget(self.line_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem26)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_2.addWidget(self.checkBox_3)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.horizontalLayout_8.addWidget(self.groupBox_2)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem27)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.line_2 = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_7.addWidget(self.line_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.spinBox = QtWidgets.QSpinBox(self.widget)
        self.spinBox.setMaximum(1000000)
        self.spinBox.setProperty("value", 1000)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_9.addWidget(self.spinBox)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_9.addWidget(self.label_8)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem28)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_9.addWidget(self.pushButton)
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem29)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_9.addWidget(self.pushButton_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(self.widget_2)
        self.tabWidget.setObjectName("tabWidget")
        self.gradienttab = QtWidgets.QWidget()
        self.gradienttab.setObjectName("gradienttab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gradienttab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.gradienttab)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.gradienttab)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.verticalLayout.addWidget(self.graphicsView_2)
        spacerItem30 = QtWidgets.QSpacerItem(20, 196, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem30)
        self.tabWidget.addTab(self.gradienttab, "")
        self.energytab = QtWidgets.QWidget()
        self.energytab.setObjectName("energytab")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.energytab)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.energytab)
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.verticalLayout_6.addWidget(self.graphicsView_4)
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.energytab)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.verticalLayout_6.addWidget(self.graphicsView_3)
        spacerItem31 = QtWidgets.QSpacerItem(20, 196, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem31)
        self.tabWidget.addTab(self.energytab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.graphicsView_6 = QtWidgets.QGraphicsView(self.tab_3)
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.verticalLayout_7.addWidget(self.graphicsView_6)
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.tab_3)
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.verticalLayout_7.addWidget(self.graphicsView_5)
        spacerItem32 = QtWidgets.QSpacerItem(20, 196, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem32)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout_8.addWidget(self.tabWidget)
        self.horizontalLayout_44 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_44.setObjectName("horizontalLayout_44")
        self.label_31 = QtWidgets.QLabel(self.widget_2)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout_44.addWidget(self.label_31)
        self.line_8 = QtWidgets.QFrame(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_8.sizePolicy().hasHeightForWidth())
        self.line_8.setSizePolicy(sizePolicy)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_44.addWidget(self.line_8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_44)
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_34 = QtWidgets.QLabel(self.widget_2)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_11.addWidget(self.label_34)
        self.label_46 = QtWidgets.QLabel(self.widget_2)
        self.label_46.setObjectName("label_46")
        self.verticalLayout_11.addWidget(self.label_46)
        self.label_45 = QtWidgets.QLabel(self.widget_2)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_11.addWidget(self.label_45)
        self.label_44 = QtWidgets.QLabel(self.widget_2)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_11.addWidget(self.label_44)
        self.horizontalLayout_45.addLayout(self.verticalLayout_11)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_33 = QtWidgets.QLabel(self.widget_2)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_10.addWidget(self.label_33)
        self.label_43 = QtWidgets.QLabel(self.widget_2)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_10.addWidget(self.label_43)
        self.label_42 = QtWidgets.QLabel(self.widget_2)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_10.addWidget(self.label_42)
        self.label_41 = QtWidgets.QLabel(self.widget_2)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_10.addWidget(self.label_41)
        self.label_40 = QtWidgets.QLabel(self.widget_2)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_10.addWidget(self.label_40)
        self.horizontalLayout_45.addLayout(self.verticalLayout_10)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_39 = QtWidgets.QLabel(self.widget_2)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_9.addWidget(self.label_39)
        self.label_37 = QtWidgets.QLabel(self.widget_2)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_9.addWidget(self.label_37)
        self.label_36 = QtWidgets.QLabel(self.widget_2)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_9.addWidget(self.label_36)
        self.label_35 = QtWidgets.QLabel(self.widget_2)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_9.addWidget(self.label_35)
        self.label_32 = QtWidgets.QLabel(self.widget_2)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_9.addWidget(self.label_32)
        self.horizontalLayout_45.addLayout(self.verticalLayout_9)
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_45.addItem(spacerItem33)
        self.verticalLayout_8.addLayout(self.horizontalLayout_45)
        spacerItem34 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem34)
        self.horizontalLayout_10.addWidget(self.widget_2)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Cavity"))
        self.label_9.setText(_translate("Form", "Frequency [MHz]"))
        self.label_10.setText(_translate("Form", "R/Q [Ohm]"))
        self.label_12.setText(_translate("Form", "Q0"))
        self.label_11.setText(_translate("Form", "Length [m]"))
        self.label_13.setText(_translate("Form", "Detuning [Hz]"))
        self.label_14.setText(_translate("Form", "Detuning angle [deg]"))
        self.label_2.setText(_translate("Form", "Coupling"))
        self.label_15.setText(_translate("Form", "Qext"))
        self.label_18.setText(_translate("Form", "Beta"))
        self.label_16.setText(_translate("Form", "Line impedance [Ohm]"))
        self.label_17.setText(_translate("Form", "Turn ratio n"))
        self.label_4.setText(_translate("Form", "Filling"))
        self.label_19.setText(_translate("Form", "Time [ms]"))
        self.label_22.setText(_translate("Form", "Steady state gradient  [MV/m]"))
        self.label_21.setText(_translate("Form", "Fwd Voltage [V]"))
        self.label_20.setText(_translate("Form", "Fwd Power [W]"))
        self.checkBox_5.setText(_translate("Form", "Lock with flattop"))
        self.label_3.setText(_translate("Form", "Flattop"))
        self.label_25.setText(_translate("Form", "Fwd Voltage [V]"))
        self.label_23.setText(_translate("Form", "Time [ms]"))
        self.label_24.setText(_translate("Form", "Fwd Power [W]"))
        self.label_26.setText(_translate("Form", "Steady state gradient [MV/m]"))
        self.label_5.setText(_translate("Form", "Decay"))
        self.label_29.setText(_translate("Form", "Time [ms]"))
        self.label_28.setText(_translate("Form", "QL"))
        self.label_27.setText(_translate("Form", "Bandwidth [Hz]"))
        self.label_30.setText(_translate("Form", "Tau [ms]"))
        self.label_38.setText(_translate("Form", "Time [x tau]"))
        self.label_6.setText(_translate("Form", "Show"))
        self.groupBox_2.setTitle(_translate("Form", "Displayed traces"))
        self.checkBox_3.setText(_translate("Form", "Probe"))
        self.checkBox_2.setText(_translate("Form", "Forward"))
        self.checkBox.setText(_translate("Form", "Reflected"))
        self.label_7.setText(_translate("Form", "Simulation"))
        self.label_8.setText(_translate("Form", "Simulation points"))
        self.pushButton.setText(_translate("Form", "Load"))
        self.pushButton_2.setText(_translate("Form", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gradienttab), _translate("Form", "Gradient/Voltage"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.energytab), _translate("Form", "Energy/Power"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Phase"))
        self.label_31.setText(_translate("Form", "Consumption"))
        self.label_34.setText(_translate("Form", "Filling diss. energy [mJ]"))
        self.label_46.setText(_translate("Form", "Flattop diss. energy [mJ]"))
        self.label_45.setText(_translate("Form", "Decay diss. energy [mJ]"))
        self.label_44.setText(_translate("Form", "Total diss. energy [mJ]"))
        self.label_33.setText(_translate("Form", "TextLabel"))
        self.label_43.setText(_translate("Form", "TextLabel"))
        self.label_42.setText(_translate("Form", "TextLabel"))
        self.label_41.setText(_translate("Form", "TextLabel"))
        self.label_40.setText(_translate("Form", "TextLabel"))
        self.label_39.setText(_translate("Form", "TextLabel"))
        self.label_37.setText(_translate("Form", "TextLabel"))
        self.label_36.setText(_translate("Form", "TextLabel"))
        self.label_35.setText(_translate("Form", "TextLabel"))
        self.label_32.setText(_translate("Form", "TextLabel"))

